- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-cli/src/main/webapp/WEB-INF/layouts/overall.ssp
- mango-cli/src/main/webapp/WEB-INF/layouts/reads.ssp
- mango-cli/src/main/webapp/WEB-INF/layouts/variants.ssp
- mango-cli/src/main/webapp/js/freq.js
- mango-cli/src/main/webapp/js/reads.js
- mango-cli/src/main/webapp/js/variants.js
Major speedup from more efficient data binding to visualization elements.
Also minor style fixes and changes.
> speedup from more efficient binding of data

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-cli/src/main/webapp/WEB-INF/layouts/features.ssp
- mango-cli/src/main/webapp/WEB-INF/layouts/overall.ssp
- mango-cli/src/main/webapp/WEB-INF/layouts/reads.ssp
- mango-cli/src/main/webapp/css/style.css
- mango-cli/src/main/webapp/js/features.js
- mango-cli/src/main/webapp/js/overall.js
- mango-cli/src/main/webapp/js/reads.js
Current Color Scheme:
G: Dark Green
C: Red
A: Blue
T: Orange
> Visualizes Reference Concurrently with Reads, Overall Displays Everything Concurrently

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
> Speedup from caching data, speedup in freq calculation

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
> Added in projections when loading files

- pom.xml
Instead of transitive dependency. Should resolve an issue reported on the [ADAM mailing list](https://groups.google.com/forum/#!topic/adam-developers/LnTFx2C8rhY).
> Adding explicit dependency on jetty-server

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
As a result, the `-print_metrics` option in `mango-submit` now works as well.
> added in quit to stop server, added logging to server and file load

- mango-cli/src/main/webapp/js/overall.js
- mango-cli/src/main/webapp/js/reads.js
http://www.bioinformatics.org/jmol-tutorials/jtat/_docs/qcolors.htm
> Added Standardized Base Colors for DNA Reference

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-core/src/main/scala/org/bdgenomics/mango/models/TrackedLayout.scala
> Implemented Fasta Indexing

- mango-cli/src/main/webapp/WEB-INF/layouts/freq.ssp
- mango-cli/src/main/webapp/js/freq.js
- mango-cli/src/main/webapp/js/overall.js
Now with 100% more animation!!
Performs d3 update correctly to update objects on screen if the region changes rather than completely removing and rendering for every region. Resolves #48.
> Performs D3 Update Correctly

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-cli/src/main/webapp/css/style.css
- mango-cli/src/main/webapp/js/overall.js
Aligned Reverse Strand to Right (readNegativeStrand is true), Red Arrow
Aligned Forward Strand to Left (readNegativeStrand is false), Green Arrow
Solves #26
> Visualizes Read Orientation

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-cli/src/main/webapp/js/overall.js
Applies to Reference, Variants, Features, Reads
Resolves #29
> Click Visual Elements for More Information

- mango-cli/pom.xml
- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-core/pom.xml
- pom.xml
> Upgraded parquet to 1.8.1 to correctly support filter predicates

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-cli/src/main/webapp/WEB-INF/layouts/overall.ssp
- mango-cli/src/main/webapp/WEB-INF/layouts/reads.ssp
- mango-cli/src/main/webapp/css/style.css
- mango-cli/src/main/webapp/js/overall.js
> Checkboxes for indels and mismatches

- mango-cli/src/main/webapp/WEB-INF/layouts/features.ssp
- mango-cli/src/main/webapp/WEB-INF/layouts/freq.ssp
- mango-cli/src/main/webapp/WEB-INF/layouts/reads.ssp
- mango-cli/src/main/webapp/WEB-INF/layouts/variants.ssp
- mango-cli/src/main/webapp/js/freq.js
Resolves #64, also uses single request box for reads, variants, features, freq (previously only overall).
> [MANGO-64] Freq tooltip

- bin/compute-mango-jars.sh
- bin/mango-submit
- pom.xml
Resolves #68. Ran with Spark 1.4.1.
Note: Jetty Server Updated to work with Spark 1.4.1. Also uses ADAM 0.17.1.
> [MANGO-68] Spark Upgrade

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-cli/src/main/webapp/WEB-INF/layouts/overall.ssp
- mango-cli/src/main/webapp/WEB-INF/layouts/variants.ssp
- mango-cli/src/main/webapp/js/overall.js
- mango-cli/src/main/webapp/js/reads.js
- mango-cli/src/main/webapp/js/reference.js
- mango-cli/src/main/webapp/js/utilities.js
- mango-cli/src/main/webapp/js/variants.js
- mango-cli/src/main/webapp/stylesheets/main.css
- mango-cli/src/main/webapp/stylesheets/main.scss
- mango-core/src/main/scala/org/bdgenomics/mango/layout/AlignmentRecordLayout.scala
- mango-core/src/main/scala/org/bdgenomics/mango/layout/FeatureLayout.scala
- mango-core/src/main/scala/org/bdgenomics/mango/layout/MismatchLayout.scala
- mango-core/src/main/scala/org/bdgenomics/mango/layout/Track.scala
- mango-core/src/main/scala/org/bdgenomics/mango/layout/TrackedLayout.scala
- mango-core/src/main/scala/org/bdgenomics/mango/layout/VariantLayout.scala
- mango-core/src/main/scala/org/bdgenomics/mango/models/LazyMaterialization.scala
- mango-core/src/test/scala/org/bdgenomics/mango/layout/AlignmentRecordLayoutSuite.scala
- mango-core/src/test/scala/org/bdgenomics/mango/layout/FeatureLayoutSuite.scala
- mango-core/src/test/scala/org/bdgenomics/mango/layout/FrequencyLayoutSuite.scala
- mango-core/src/test/scala/org/bdgenomics/mango/layout/MismatchLayoutSuite.scala
- mango-core/src/test/scala/org/bdgenomics/mango/layout/VariantLayoutSuite.scala
- mango-core/src/test/scala/org/bdgenomics/mango/models/LazyMaterializationSuite.scala
Modified mismatch calculations and removed groupby for alignment json calculation
> Mismatches

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-cli/src/main/webapp/WEB-INF/layouts/overall.ssp
- mango-cli/src/main/webapp/js/overall.js
- mango-cli/src/main/webapp/js/reads.js
- mango-cli/src/main/webapp/js/utilities.js
- mango-core/src/main/scala/org/bdgenomics/mango/filters/AlignmentRecordFilter.scala
Read quality filters implemented [0-100 scale]
Filtering done via call to Spark
> Read Quality Filters

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-cli/src/main/webapp/js/overall.js
Clean up backend calls and fix asynchronous loading issues.
Note: Issue with timer still awaiting fix.
> Asynchronous Backend Changes

- .gitignore
- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-cli/src/main/webapp/js/overall.js
- mango-cli/src/main/webapp/js/reads.js
- mango-core/src/main/scala/org/bdgenomics/mango/layout/MismatchLayout.scala
- mango-core/src/main/scala/org/bdgenomics/mango/models/LazyMaterialization.scala
- mango-core/src/test/scala/org/bdgenomics/mango/models/LazyMaterializationSuite.scala
- pom.xml
Changelog:
-SequenceDictionary is now set only from the reference file (fasta, adam) 
-RDD caching for referenceRDD (for #82 and #84) and for intervalRDDs
-adds idea to gitignore to solve #103
> Global SequenceDictionary from Reference

- README.md
- mango-core/src/main/scala/org/bdgenomics/mango/models/ReferenceRDD.scala
- mango-core/src/main/scala/org/bdgenomics/mango/util/ResourceUtils.scala
- mango-core/src/test/scala/org/bdgenomics/mango/layout/AlignmentRecordLayoutSuite.scala
- pom.xml
> doesn't store reference in memory if local

- bin/mango-submit
- mango-core/src/main/scala/org/bdgenomics/mango/serialization/MangoKryoRegistrator.scala
> registering buffer classes in kryo

- mango-cli/src/main/webapp/js/d3utilities.js
- mango-cli/src/main/webapp/js/reads.js
- mango-cli/src/main/webapp/js/utilities.js
> fixed alignment and frequency bugs. Implemented wait spinner for data load

- mango-cli/src/main/webapp/js/overall.js
- mango-cli/src/main/webapp/stylesheets/main.css
- mango-cli/src/main/webapp/stylesheets/main.scss
> Frontend Bug fixes 

- mango-cli/src/main/webapp/WEB-INF/layouts/overall.ssp
- mango-cli/src/main/webapp/js/reads.js
- mango-cli/src/main/webapp/stylesheets/main.css
- mango-cli/src/main/webapp/stylesheets/main.scss
- added y axis for mismatch frequency (Issue #168)
- minor frontend fixes
> Fixed Issue #168 Mismatch frequency y axis

- mango-cli/src/main/webapp/WEB-INF/layouts/templates/head.ssp
- mango-cli/src/main/webapp/stylesheets/main.css
- mango-cli/src/main/webapp/stylesheets/main.scss
- mango-core/src/main/scala/org/bdgenomics/mango/models/AnnotationMaterialization.scala
* relinked broken stylesheet
* updates to ADAM downstream
> ADAM updates and stylesheet fix

- scripts/init-pileup
Pileup scripts now initialize git submodules
> Update pileup script to initialize git submodules

- mango-core/src/main/scala/org/bdgenomics/mango/converters/GA4GHConverter.scala
- mango-core/src/main/scala/org/bdgenomics/mango/models/AlignmentRecordMaterialization.scala
- mango-core/src/main/scala/org/bdgenomics/mango/models/AnnotationMaterialization.scala
Update code to support new avro formats
> Adam 0.19.1 Update

- mango-cli/src/main/webapp/WEB-INF/layouts/overall.ssp
> Text changes to overall

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
Resolve potential async issues in back end.
> Synchronization primitive updates to VizReads

- README.md
- mango-cli/pom.xml
- mango-core/pom.xml
- pom.xml
- scripts/jenkins-test
> [MANGO-274] Add coverage profile and set up Coveralls.

- bin/gce/install.sh
- bin/gce/run-browser.sh
- bin/gce/run-notebook.sh
- docs/cloud/google-cloud.rst
- docs/index.rst
> Google Cloud Setup

- docs/cloud/google-cloud.rst
- example-files/notebooks/gce-1000genomes.ipynb
Add billing account instructions, and minor fixes
> Update google cloud documentation 

- bin/emr/run-browser.sh
- bin/emr/run-notebook.sh
> Update emr scripts

- docs/installation/distribution.rst
Update 'wget' command in distribution docs.
The current command downloads to 
``
remotecontent?filepath=org%2Fbdgenomics%2Fmango%2Fmango-distribution%2F0.0.1%2Fmango-distribution-0.0.1-bin.tar.gz
``
> Update distribution download command

- mango-python/bdgenomics/mango/distribution.py
- mango-python/requirements.txt
- mango-viz/Makefile
- mango-viz/bdgenomics/mango/pileup/test/test_types.py
- scripts/jenkins-test
dependent on https://github.com/bigdatagenomics/adam/pull/2070 being merged and pushed to pypi
> added python3 tests for jenkins

- example-files/notebooks/mango-python-variants.ipynb
- mango-python/bdgenomics/mango/genotypes.py
- mango-python/bdgenomics/mango/test/genotypes_test.py
> Added more genotype visualizations

- mango-cli/src/main/scala/org/bdgenomics/mango/cli/VizReads.scala
- mango-cli/src/test/scala/org/bdgenomics/mango/cli/VizReadsSuite.scala
- mango-core/src/main/scala/org/bdgenomics/mango/converters/GA4GHConverter.scala
- mango-core/src/main/scala/org/bdgenomics/mango/converters/GA4GHutil.scala
- mango-core/src/main/scala/org/bdgenomics/mango/layout/Layout.scala
- mango-core/src/main/scala/org/bdgenomics/mango/models/AlignmentRecordMaterialization.scala
- mango-core/src/main/scala/org/bdgenomics/mango/models/CoverageMaterialization.scala
- mango-core/src/main/scala/org/bdgenomics/mango/models/FeatureMaterialization.scala
- mango-core/src/main/scala/org/bdgenomics/mango/models/LazyMaterialization.scala
- mango-core/src/main/scala/org/bdgenomics/mango/models/VariantContextMaterialization.scala
- mango-core/src/main/scala/org/bdgenomics/mango/serialization/MangoKryoRegistrator.scala
- mango-core/src/main/scala/org/bdgenomics/mango/util/RefSeq.scala
- mango-core/src/test/scala/org/bdgenomics/mango/converters/GA4GHConverterSuite.scala
- mango-core/src/test/scala/org/bdgenomics/mango/converters/GA4GHutilSuite.scala
- mango-core/src/test/scala/org/bdgenomics/mango/layout/LayoutSuite.scala
- mango-core/src/test/scala/org/bdgenomics/mango/models/LazyMaterializationSuite.scala
- mango-core/src/test/scala/org/bdgenomics/mango/models/VariantContextMaterializationSuite.scala
- pom.xml
Fixes #482.  Work in progress.
> Update ADAM dependency version to 0.26.0

- mango-python/version.py
- scripts/jenkins-test
deletes conda env and temporary directories on exit
> Jenkins traps for clean exit

- bin/emr/install-bdg-mango-dist-emr5.sh
- scripts/release/README.md
- scripts/release/release.sh
- add python flag to release python versions
- add documentation about releasing python
> Update release documentation

- mango-viz/bdgenomics/mango/pileup/sources.py
- mango-viz/examples/pileup-tutorial.ipynb
> removed io dependency in widgets

- mango-cli/src/main/webapp/resources/package.json
- mango-viz/bdgenomics/mango/js/css/mangoviz.css
- mango-viz/bdgenomics/mango/js/package.json
- mango-viz/bdgenomics/mango/js/src/embed.js
- mango-viz/bdgenomics/mango/js/src/pileupViewer.js
- mango-viz/bdgenomics/mango/pileup/pileupViewer.py
- mango-viz/bdgenomics/mango/pileup/test/test_application.py
- mango-viz/examples/pileup-tutorial.ipynb
- mango-viz/requirements.txt
- mango-viz/setup.py
required pileup.js update to 0.6.13
> Add programmatic zoom and svg saving to widgets

- mango-viz/requirements.txt
Fixes https://github.com/bigdatagenomics/mango/issues/
> bump modin version

- mango-viz/requirements.txt
- scripts/jenkins-test
Fixes issue in build with modin ray: AttributeError: module 'pandas' has no attribute 'core'
> updated modin version
